image: gitpod/workspace-full

tasks:
  - init: ./mvnw clean install -U -DskipTests
    name: Run PetClinic app

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack
