image: gitpod/workspace-full

tasks:
  - init: ./mvnw clean install -U -DskipTests
    command: ./mvnw spring-boot:run
    name: Run PetClinic app

ports:
  - port: 8080
    onOpen: open-preview

jetbrains:
  pycharm:
    prebuilds:
      version: both
