image: gitpod/workspace-base

tasks:
  - init: echo "this is `init`"
    command: echo "this is `command`"
    name: Task name
  - init: echo "hello"
    command: echo "world"
    name: Task 2
  - init: echo "foo"
    command: echo "boo"
    name: Task 3

ports:
  - port: 8080
    onOpen: open-preview
